### ISSUE TITLE
InsertOrReplaceAll fails on Windows Phone 8.0 (Silverlight)

### ISSUE THREAD

**Issue by eugenioestrada** [oysteinkrog/SQLite.Net-PCL#114]
Hi,

I use InsertOrReplaceAll in a Portable Class Library used in a Xamarin Android project and a Windows Phone 8.0 (Silverlight) project. In Android it works properly, but In Windows Phone 8 it throws an exception:

> An exception of type 'SQLite.Net.SQLiteException' occurred in SQLite.Net.DLL but was not handled in user code

> Additional information: SQL logic error or missing database

I've uploaded an example: https://github.com/eugenioestrada/sqlite-wp8-insertorreplaceall, I tried to debug the library code but I cannot get it run... (a problem loading the assembly on the phone :( )

**Comment by oysteinkrog** [comment]
Were you able to solve this problem?

**Comment by oysteinkrog** [comment]
Closed due to no response:/

**Comment by mpace965** [comment]
I'm having this exact same issue under similar conditions: Windows Phone 8 Silverlight Project, crashing on InsertOrReplaceAll, using guids. I've tried messing with the library code by removing the "OR REPLACE" extra. The Insert statement without "OR REPLACE," which leads me to agree with your conclusion in #138, that this is an sqlite bug, because the Insert operation doesn't run into any conflicts, so "OR REPLACE" is never used.

Or is it possible that the bug is coming from using [sqlite-net-wp8](https://github.com/peterhuene/sqlite-net-wp8) to make calls to the official sqlite, which has fallen under inactive development? Looks like the last update was for version 3.8.5 of the official dll, current version is 3.8.10.2. If this is the case, I'm not really sure what to look for.

**Comment by igrali** [comment]
@mpace965 did you try using the old Visual Studio extension for SQLite, v3.8.1? http://igrali.com/2015/04/01/sqlite-logic-error-or-missing-database-now-what/

**Comment by mpace965** [comment]
Hey, that works perfectly! Thanks!
