### ISSUE TITLE
Create one NuGet package

### ISSUE THREAD

**Issue by aloisdeniel** [oysteinkrog/SQLite.Net-PCL#132]
Instead of having a different NuGet package for each platform, why not using one package that contains all the .dll ?

MvvmLight did this for example : [MvvmLight nuspec file](https://mvvmlight.codeplex.com/SourceControl/latest#NuGet/MvvmLightLibs.V5.nuspec)

**Comment by oysteinkrog** [comment]
Yeah, I've had an earlier request for this as well, and I think I agree that it might be a better solution.
Unfortunately I don't have too much time to spend on this project so I am not doing any active development.
If you want to work on this feel free to send a PR and I will review it:)

**Comment by oysteinkrog** [comment]
I've merged your PR, thank you:)
I decided to merge since overall this new unified package is quite clearly a win for the users.
I am a little bit worried about what the story for transitioning all the existing users of the old platform packages will be though. 
I suppose we should at the very least include a note, but ideally we would make it automatic, though I'm not sure how much work that would be to implement.
