### ISSUE TITLE
Saving DateTime value is adding 4 hours version 3.0.5

### ISSUE THREAD

**Issue by ataria2** [oysteinkrog/SQLite.Net-PCL#184]
I have update from version 2.5.1 to 3.0.5 and when I save a DateTime is adding 4 hours.

**Comment by oysteinkrog** [comment]
The new behavior is that DateTime is always serialized and deserialized in UTC format (dateTimeVar.Kind). This breaking change (hence the major version bump) was done because the old code would _lose_ datetime zone/kind information which is not acceptable.
If you need "local" time values from db data call ToLocalTime() on your datetime objects.

**Comment by ataria2** [comment]
Thanks for the fast reply.
