### ISSUE TITLE
SQLite.Net 3.0.5 DateTime locale issue

### ISSUE THREAD

**Issue by salvods** [oysteinkrog/SQLite.Net-PCL#219]
Hello,

We are experiencing some problem after upgrading to version 3.0.5, in particular all the fields of type "DateTime" (which we store as ticks) are stored wrong, it seems the locale is ignored.

In the following link you can find a sample project that reproduce this issue: https://goo.gl/0usCPK

Thanks for the great work and support

**Comment by oysteinkrog** [comment]
Hmm, if you store as ticks that means locale was never stored and is also not stored with the new breaking changes in 3.0.
I added the below text to the readme when this change was made:

* DateTime serialization
DateTime serialization is changed, in order to be consistent. When using the storeDateTimeAsTicks option, the DateTime is now serialized as Utc, and the returned DateTime is also in Utc. You can get the local time by using dateTime.ToLocalTime()
